### ISSUE TITLE
Story: Create Error Page for when API Fails

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#110]
## As a user, I need to encounter an error page when a call to the API fails.

> **ESTIMATE** XX

### Acceptance Criteria

```gherkin
Scenario: User encounters an error page when API fails
  Given user is navigating to any page within the dictionary app
   And the API is not returning data
  When user loads the page
    Then  the user gets an error page that reads "An error occurred. Please try again later."
```
```gherkin
Scenario: User encounters an error page when API fails in Spanish
  Given the language is set to ES
  Given user is navigating to the Spanish dictionary landing page
  And the API is not returning data
  When user loads the page 
    Then  the user gets an error page that reads "Se produjo un error. Por favor, vuelva a intentar más tarde."
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/413568379_DICTIONARY_OF_CANCER_TERMS_RESULTS_Error_-_Desktop_HD_-_1441_--_1025
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by blilianyu** [comment]
Comps have been added.
