### ISSUE TITLE
Space missing between Term and phonetic spelling

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/glossary-app#114]
### Issue description
Space is missing between a term that doesn’t have an audio but a phonetic spelling

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  Search for mammary duct ectasia

### What's the expected result?
- There should be a space between the term and phonetic spelling

### What's the actual result?
- There is no space between the term and phonetic spelling

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/51677926/78900600-11e87300-7a45-11ea-9c27-6e5cace78777.png)

**Comment by bryanpizzillo** [comment]
This was not actually fixed in PR144. Reopening.
