### ISSUE TITLE
Language toggle in React App should toggle

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#123]
### Language toggle in React App should work
The language toggle in the react app right now does not work, so the user has to use the dropdown to switch languages.  We should be able to click the toggle to switch over to Spanish (especially since this works on local machines)

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to react-app-dev
2. On the Dictionary of Cancer Terms, click "Language toggle" 
3. Note that you are not taken to the spanish dictionary landing page

### What's the expected result?
Clicking on the Language toggle should take me to the Spanish landing page

### What's the actual result?
Right now, I'm taken to page not found

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by amydugan** [comment]
During Sprint 8 Planning, we discussed that this bug is actually a non-issue and should be closed.
