### ISSUE TITLE
Speaker Icon Cut off on IE11

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/glossary-app#187]
### Issue description
The speaker icons appear to be cut off at the bottom on IE11.

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  Go to www-dev-ascf.cancer.gov/dictionaries/cancer-terms
2. Scroll down to words that have audio pronunciations 

### What's the expected result?
- Icon should not be cut off by the row below it

### What's the actual result?
- Icon bottom tip is missing - either getting clipped by overflow or other element.

### Additional details / screenshot
- ![IMG_8858](https://user-images.githubusercontent.com/66697447/87063086-df811a00-c1db-11ea-8885-0d6293e8edce.jpg)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
We no longer support IE, so closing this ticket.
