### ISSUE TITLE
Audio takes long to play on IE

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#189]
### Issue description
**
On IE, It takes about 1.5 - 3 minutes for audio to play when the browser is loaded the first time. 

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/publications/dictionaries/cancer-terms on IE.
2. Click any audio icon appearing with a term ( For example, click the audio icon with the term "AAT deficiency")
3. The audio will NOT play right away. Wait for about 1.5 minutes for the audio to play.

### What's the expected result?
- The audio should play right away on clicking the audio icon. 

### What's the actual result?
-The audio is played after about 1.5 minutes

![image](https://user-images.githubusercontent.com/28455973/87174126-bed0c700-c2a4-11ea-8c25-3c040addb48e.png)

**Comment by sarinapadilla** [comment]
We no longer support IE, so closing this ticket.
