### ISSUE TITLE
The landing page of Dictionary of Cancer Terms is not loading correctly on Edge

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#190]
### Issue description
On Edge, the definitions are not loaded on the landing page of Dictionary of Cancer Terms and no letter or links are clickable on the page. The page hangs as soon as we go to the landing page (https://www.cancer.gov/publications/dictionaries/cancer-terms) on Edge and user is unable to navigate to any other page including the Drug Dictionary and Genetics Dictionary.  On Edge, when Ithe url https://www.cancer.gov/publications/dictionaries/cancer-terms/expand/G is pasted, the definitions appear and then when a particular term is clicked, we are redirected to the expected term definition page (https://www.cancer.gov/publications/dictionaries/cancer-terms/def/gabapentin)  and then we able to see the definition. The delay in audio issue exits on Edge (Issue #189 ).

Note: This issue prevents user to navigate to the Drug Dictionary and Genetics Dictionary from the left navigation on Edge. User can only visit Drug Dictionary and Genetics Dictionary by copying and pasting the url.

See the screenshot for the Edge version where the issue is seen.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/publications/dictionaries/cancer-terms on Edge.
2. The definitions with the letter 'A' are not visible on the page and on clicking any letter (for example, 'A' ) a message "cancer.gov is not responding" appears. Clicking on any link on the left nav does NOT do anything.

### What's the expected result?
-The dictionary page should load with all definitions.
-The letters should be clickable and user should see definitions starting with the letter clicked.
- The left nav items should be clickable and user should be redirected to the expected page.

### What's the actual result?
-The definitions with the letter 'A' are not visible on the page.
- Clicking any letter (for example, 'A' ) a message "cancer.gov is not responding" appears. 
- Clicking on any link on the left nav does NOT do anything.

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/87166208-3993e500-c299-11ea-811d-efd2d86b57f4.png)

![image](https://user-images.githubusercontent.com/28455973/87166258-487a9780-c299-11ea-950a-092ba9964ece.png)

![image](https://user-images.githubusercontent.com/28455973/101208925-e2741f80-3640-11eb-9b6e-1f2c0064d1b0.png)

### Related Tickets
* Issue #189

**Comment by seyilonge-nci** [comment]
### **Resolution:** 
This wouldn't be fixed.

### **Reason:** 
This issue applies to just MS Edge 18 (Edge Legacy), in particular the version 

_Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763_

Other versions tested preceding and subsequent do not exhibit this issue.

Also, taking a look at recent browser analytics for cancer.gov, Edge Legacy constitutes a low percentage of visitors. Within a 30 day period, Edge Legacy users were 1.1% of site visitors. For users with this Edge Legacy version, they would constitute a portion (probably very low) of the 1.1%. And the fact that Edge Legacy would also be [sunset in March 2021](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)

**Comment by seyilonge-nci** [comment]
### **Resolution:** 
This wouldn't be fixed.

### **Reason:** 
This issue applies to just MS Edge 18 (Edge Legacy), in particular the version 

_Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763_

Other versions tested preceding and subsequent do not exhibit this issue.

Also, taking a look at recent browser analytics for cancer.gov, Edge Legacy constitutes a low percentage of visitors. Within a 30 day period, Edge Legacy users were 1.1% of site visitors. For users with this Edge Legacy version, they would constitute a portion (probably very low) of the 1.1%. And the fact that Edge Legacy would also be [sunset in March 2021](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)
