### ISSUE TITLE
More information on dictionary page link from sitewide search results not going to definition page

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/glossary-app#191]
### Issue description
The more information on dictionary page link with the query parameter on sitewide search results for dictionary terms is not routing to the term definition as expected. Instead, the user is sent to the Dictionary of Cancer Terms landing page. 

When a user searches for a keyword in sitewide search that happens to be a term in the Dictionary of Cancer terms, the top of the results page includes a truncated version of the term definition with a more information on dictionary page link that should link to the term definition page. 

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Enter "keytruda" in the sitewide search box
2. Click on the More information on dictionary page link under the truncated keytruda definition
3. Link goes to the Dictionary of Cancer Terms landing page

### What's the expected result?
-When a user searches for a keyword in sitewide search that happens to be a term in the Dictionary of Cancer terms (in this scenario, Keytruda) ,the top of the results page includes a truncated version of the term definition with a more information on dictionary page link that should link to the term definition page for Keytruda https://www.cancer.gov/publications/dictionaries/cancer-terms/def/keytruda. 

### What's the actual result?
- The link, which includes the query parameters (https://www.cancer.gov/publications/dictionaries/cancer-terms?CdrID=764540) resolves to the Dictionary of Cancer Terms landing page instead of resolving to the term definition page. 

### Additional details / screenshot
- ![Screenshot]()
![image](https://user-images.githubusercontent.com/28450779/87182942-1e35d380-c2b3-11ea-8fd8-b83c9b8b1f52.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
This should be a ticket for cgov-digital-platform. However, since we are rebuilding the Site Wide Search app AND we will fix the backwards compatibility issue, there is no reason to fix this in the current .NET code.

**Comment by bryanpizzillo** [comment]
Closed by #193
