### ISSUE TITLE
User is not directed to page with list of term definitions when there is one term definition for a letter 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#192]
### Issue description
Currently - if a user clicks on a letter that only has one definition, the user is brought directly to the term definition page for the single term in that letter instead of the expand page for the letter selected.

The expected behavior is that the user is taken to the expand page for the selected letter.

Example:
On Production, in the genetics dictionary, clicking on the "k" link leads the user to https://www.cancer.gov/publications/dictionaries/genetics-dictionary/def/kindred instead of /publications/dictionaries/genetics-dictionary/expand/K

Acceptance Criteria:
Given the user is on the Dictionary of Genetics Terms
  When the user clicks on "K" in the browse list
    Then the system should display /expand/K 

**Note:** I think this may be the only example for now on Production - and an edge case due to the requirement we put in place where if the searched for term is the only matching term in the dictionary, we return the term page instead of the search results page.

**Comment by blairlearn** [comment]
Just to be clear, this is Expand versus Search.

**Comment by VictoriaSunNIH** [comment]
This sounds like a bug in the system.  Updated the ticket to reflect what it is we're looking for.

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH  This is actually due to how the implementation was done. Expand and Search share the same code. If there are any other expand vs search differences they should be thoroughly tested to make sure there are no other bugs.
