### ISSUE TITLE
Remove Language Toggle for Glossary Terms without Translation

### ISSUE THREAD

**Issue by venglisch** [NCIOCPL/glossary-app#195]
### Issue description
As part of our dictionary we have a few terms for which there doesn’t exist a Spanish translation.  “windpipe” is one of those terms.  Currently, the CDR is forcing a Spanish translation by using the English name and adding (in English) after the English term name.  For example see the following link:
    https://www.cancer.gov/espanol/publicaciones/diccionario/def/windpipe-en-ingles

The users would like to remove these artificially created Spanish terms.  This will create glossary terms without a translation.  

I have tested the change on DEV, removed the "en ingles" terms and loaded the updated dictionary.  With the new dictionary, the term "windpipe" is still displaying the "Spanish" language toggle although a translation for the displayed term does not exist. 
The users would like the toggle to be displayed only when a translation does exist.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Ensure you are working with a dictionary that has the "en ingles" terms removed, i.e. DEV
2. Open the Spanish dictionary page and search for terms that contain "en ingl"
3. If there are zero results for the above search switch to the English dictionary and search for "windpipe" or "EKG"
   These terms should not display the language toggle.

### What's the expected result?
- No language toggle is displayed for windpipe, or EKG

### What's the actual result?
- A language toggle is displayed

### Additional details / screenshot
- Currently, *all* dictionary terms have a translation.

**Comment by arcepaul** [comment]
So the approach would be to take control of the toggle.  We would need to check for the existence of the toggle and add it for each view if it does not exist.

**Comment by venglisch** [comment]
The end-users reported that the need for this change is not as urgent as it once was.  I'm quoting CIAT's comment to the corresponding CDR ticket:
"Currently there is only **one** dictionary term (PI) that meets the issue reported in this ticket."

**Comment by venglisch** [comment]
The related CDR ticket (OCECDR-4349) has been closed.  Feel free to do the same with this ticket.
We're not expecting to address the issue for a single dictionary term.

**Comment by sarinapadilla** [comment]
Closing this ticket based on Volker's comment above!
