### ISSUE TITLE
On clicking the language toggle, returning to Spanish Dictionary of Cancer Terms (form) from a English Term definition page instead of returning to the Spanish Term definition page 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#198]
### Issue description
*When we go to the url https://www.cancer.gov/publications/dictionaries/cancer-terms/def/childhood-acute-lymphoblastic-leukemia-risk-group-system and click the Espanol link  for language toggle , we are directed to the Spanish version of Dictionary of Cancer Terms page with the following url:
https://www.cancer.gov/espanol/publicaciones/diccionario?app_module_route=/def&app_module_data%5BanalyticsName%5D=CancerTerms&app_module_data%5Baudience%5D=Patient&app_module_data%5BdictionaryName%5D=Cancer.gov&app_module_data%5BdictionaryIntroText%5D=%3Cp%3EThe%20NCI%20Dictionary%20of%20Cancer%20Terms%20features%20%3Cstrong%3E%7B%7Bterm_count%7D%7D%3C/strong%3E%20terms%20related%20to%20cancer%20and%20medicine.%3C/p%3E%3Cp%3EWe%20offer%20a%20widget%20that%20you%20can%20add%20to%20your%20website%20to%20let%20users%20look%20up%20cancer-related%20terms.%20%3Ca%20href%3D%22/syndication/widgets%22%3EGet%20NCI%27s%20Dictionary%20of%20Cancer%20Terms%20Widget%3C/a%3E.%3C/p%3E&app_module_data%5BdictionaryTitle%5D=NCI%20Dictionary%20of%20Cancer%20Terms&app_module_data%5BsearchBoxTitle%5D=Search%20NCI%27s%20Dictionary%20of%20Cancer%20Terms&app_module_id=cgov_glossary_app&idorname=childhood-acute-lymphoblastic-leukemia-risk-group-system*

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/publications/dictionaries/cancer-terms/def/childhood-acute-lymphoblastic-leukemia-risk-group-system
2. Click the "Espanol" link for language toggle.

### What's the expected result?
-If the term definition exists in Spanish then the Spanish Term definition page should be loaded

### What's the actual result?
-The Spanish Dictionary of Cancer Terms page (form) loads with incorrect url

**Comment by SupriyaSaxena0605** [comment]
same thing happening for /publications/dictionaries/cancer-terms/def/jak2-gene

**Comment by sarinapadilla** [comment]
Both of the terms listed in this ticket do not have Spanish translations. Closing this ticket as we have #195 describing the issue.
