### ISSUE TITLE
Story: CDR ID on Definition Page

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#2]
## As a CDR manager, I would like to be able to find the CDRID of a definition on the definition page so that I can quickly locate the definition within the CDR system.

> **ESTIMATE** 1

### Acceptance Criteria

```gherkin
Scenario: As a CDR manager, I would like to be able to find the CDRID of a definition on the definition page so that I can quickly locate the definition within the CDR system.
  Given the user is viewing the definition with the pretty url "metastatic"
  Then there should be a "data-cdr-id" attribute on the definition's title element
```

### Notes

* This was an agreed upon solution to the fact that we no longer display the cdrid in the url for terms anymore. This caused an issue when the editors needed to be able to find the ID of a definition that needed updating.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Closing this story - the acceptance criteria for this one has been rolled into #15
