### ISSUE TITLE
Screen flicker when the "alert drawer" is scrolled off.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/glossary-app#202]
### Issue description
Just as the "alert drawer" scrolls out of visibility, the top of the page begins "flickering" alternating between the bottom of the drawer and the NCI logo. 

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Browse to https://www.cancer.gov/publications/dictionaries/cancer-terms
2. Expand the browser past the desktop/full-size breakpoint.
3. Click on a letter to expand (not 100% sure this step is required).
4. Scroll down with either the arrow keys or the mouse wheel.
5. Continue scrolling until the "alert drawer" just barely disappears.

### What's the expected result?
- The alert drawer disappears.

### What's the actual result?
- Flashing area at the top of the screen.
  **NOTE:** The actual flashing is _significantly faster_ than what shows in the "screenshot".

### Additional details / screenshot
- ![flickering-alert-drawer](https://user-images.githubusercontent.com/21063180/89557613-10f00400-d7e1-11ea-9580-ec4efefadb3b.gif)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This can no longer be reproduced with the rollout of MVP1 of redesign. Closing this ticket.
