### ISSUE TITLE
The blue background/highlight color on the first Autosuggest term does not appear for "Contains"

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#205]
### Issue description
*Description of the issue*
The blue background/highlight color on the first Autosuggest term does not appear for "Contains"

> **ESTIMATE** 20

### Steps to reproduce the issue

1. Go to https://www.cancer.gov/publications/dictionaries/cancer-terms/search/sal/?searchMode=Contains 
2. Erase "l" from the searched term "sal" in the search input box and and type "l" again in the search input box. 
3. The blue background color on the first autosuggest term does not appear.

### What's the expected result?
-The blue background/highlight color on the first autosuggest term should appear.

### What's the actual result?
- The blue background/highlight color on the first autosuggest term does not appear.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/92810842-e834ce80-f38b-11ea-8b47-062e95370d26.png)

![image](https://user-images.githubusercontent.com/28455973/92811162-321db480-f38c-11ea-8ebb-90a6d23167d9.png)

- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
Closing this - we are changing the behavior of the highlight based on requirements in #220
