### ISSUE TITLE
Redirect to PrettyUrl is missing '?redirect=true' query parameter 

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/glossary-app#206]
### Issue description
When system is redirecting user from def/CDRId to def/prettyUrlName the url should have appended query param **redirect=true**

```gherkin
Scenario: Redirect from CDR ID
  Given user enters /def/46722 as the URL
  Then the system redirects user to /def/a33
  And the system appends '?redirect=true' to the URL
```

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  go to https://www.cancer.gov/publications/dictionaries/cancer-terms/def/46722

### What's the expected result?
-/def/a33?redirect=true

### What's the actual result?
-/def/a33

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
Looks good on test-acsf.

**Comment by mworrest** [comment]
Looks good to me as well.
