### ISSUE TITLE
Change Text in Spanish

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/glossary-app#208]
### Issue description
Ensure that the following text is updated:
**Dictionary App**
**Current**: "Escriba frase o palabra clave"
**New**: "Escribir frase o palabra"
**Current**: "Ojear"
**New**: "Navegar por letra inicial"
**Current**: "Busca diccionario de cáncer"	
**New**:Consulte el Diccionario de cáncer del NCI.

> **ESTIMATE** 20

### What's the expected change?
- New text to replace the current text.

### What's the current functionality?
- Text that the Spanish team wants replaced.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* https://tracker.nci.nih.gov/browse/CGOV-12443

**Comment by amydugan** [comment]
Removed Dictionary Glossary Widget Spanish Text Updates from Ticket and moved to separate ticket in Glossary Widget Repo: https://github.com/NCIOCPL/glossary-widget/issues/2

**Comment by mworrest** [comment]
I see "Buscar en el diccionario de cáncer del NCI" instead of "Consulte el Diccionario de cáncer del NCI"

on https://www-test-acsf.cancer.gov/espanol/publicaciones/diccionarios/diccionario-cancer/def/d-20761

**Comment by alinai** [comment]
I am seeing the same as @mworrest

**Comment by alinai** [comment]
Looks good to me on ODE.
