### ISSUE TITLE
Update search box functionality to be consistent with Drug Dictionary

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/glossary-app#220]
### Issue description
- The Search button is not full width like it is on drug dictionary.
- Autosuggest dropdown should be dropped either at the button or above search box based on screen
-  Remove auto highlight of the first autosuggest item - to enable users to hit enter and search without selecting an item

> **ESTIMATE** TBD

### What's the expected change?
-The search button should be full width on mobile (<641).
- no autohighlight of first item
- dropdown changes its position based on a screen

### What's the current functionality?
-The search button is not full width on mobile.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
https://react-app-dev.cancer.gov/drug-dictionary-app/pr-81/def/bevacizumab 

### Related Tickets
* https://github.com/NCIOCPL/drug-dictionary-app/issues/57

**Comment by mworrest** [comment]
Autosuggest covers the search button on mobile so this won't work. Because autosuggest only shows 10 options, if the user's option isn't listed, they will need to hit the search button.

**Comment by KateMashkinaNIH** [comment]
This was resolved by removing auto highlighting of fist autosuggest item in drug dictionary (ref to https://github.com/NCIOCPL/drug-dictionary-app/issues/57) - thus I am reopening this change request as it is valid
