### ISSUE TITLE
Dictionary Term getting cut off by Speaker Icon

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/glossary-app#231]
### Issue description
Dictionary term is getting cut off by speaker icon.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/glossary-app/pr-228/def/b-lymphocyte
2. Or on live site: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/b-lymphocyte

### What's the expected result?
- Speaker icon doesn't cut off term

### What's the actual result?
- Speaker icon cuts off term

### Additional details / screenshot
Background color on .btnAudio needs to be set to transparent instead of #fff
<img width="1448" alt="Screen Shot 2021-02-02 at 3 22 40 PM" src="https://user-images.githubusercontent.com/51677926/106657840-83605780-656a-11eb-92f6-888505ce7649.png">

**Comment by sarinapadilla** [comment]
This issue no longer exists on Prod, so closing this ticket.
