### ISSUE TITLE
Hotfix for search box functionality 

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/glossary-app#236]
### Issue description
*The release testing on test-acsf revealed broken styling on the search box - the dropdown was detached from the search box or overlapping(covering) the box*

Also mobile breakpoint spacing is too big between search box and search button

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Focus on the search box by clicking inside - helper text is detached as well as any search results
2.  Resize the screen to mobile - spacing is too big between box and button
3. 

### What's the expected result?
- its a part of the box ( no overlap or detaching) 
- smaller spacing on mobile
### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()
ACTUAL:
- 
![overlap](https://user-images.githubusercontent.com/56886837/112648609-122d7a00-8e20-11eb-9764-2deed45bb002.png)
![space-dropdown](https://user-images.githubusercontent.com/56886837/112648625-15c10100-8e20-11eb-9b07-b7ccb701dfdf.png)

![space-on-mobile](https://user-images.githubusercontent.com/56886837/112648645-19548800-8e20-11eb-8ce2-c6db01a778b3.png)

EXPECTED: 

-
<img width="631" alt="Screen Shot 2021-03-26 at 10 44 40 AM" src="https://user-images.githubusercontent.com/56886837/112648977-68022200-8e20-11eb-8691-4dcba9f231a1.png">

<img width="802" alt="Screen Shot 2021-03-26 at 10 44 20 AM" src="https://user-images.githubusercontent.com/56886837/112648999-6cc6d600-8e20-11eb-8bb2-cb3aa8869bf5.png">

### Related Tickets
* Issue #
* Issue #9999

**Comment by sarinapadilla** [comment]
This was fixed with the hotfix (#235) so closing this ticket.
