### ISSUE TITLE
Double slash in the url returns blank page

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#240]
### Issue description
*Description of the issue*
If there is double slash in the url, a blank page is returned.

> **ESTIMATE** TBD

### Steps to reproduce the issue
1.  Go to https://www.cancer.gov/publications/dictionaries//cancer-terms 
2. We will see a blank page

### What's the expected result?
-

### What's the actual result?
- A blank page appears.

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/28455973/115465860-3ac94980-a1fd-11eb-87a8-ac01664f54c6.png)

### Related Tickets
* Issue #9999
* Issue #9999

Notes: This happens for 
https://www.cancer.gov/about-cancer/treatment//clinical-trials/search
https://www.cancer.gov/publications/dictionaries//genetics-dictionary

@VictoriaSunNIH, please update the ticket with the expected result

**Comment by sarinapadilla** [comment]
The page is returning a 404 and displaying the PNF on Prod now. Closing this ticket as it's no longer an issue!
