### ISSUE TITLE
Story: Display More Information Links on Term Page

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#25]
## As a user, I want to be able to view more information related to a specific term, so that I may expand my knowledge on a topic

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: The user views a definition with a glossary resource
  Given the user is viewing the definition with the pretty url "fatty-breast-tissue"
  Then there is a heading on the page with "More Information"
     And there is a link to a definition with the pretty url "breast-density" and the text "breast density" following the text "Definition of:"
```
```gherkin
Scenario Outline: The user views a definition with a summary link resource
  Given the user is viewing the definition with the pretty url "terminal-cancer"
  Then there is a heading on the page with "More Information"
     And there is a link to "<link>" with the text "<text>"
Examples:
|link|text|
|https://www.cancer.gov/about-cancer/advanced-cancer/care-choices/care-fact-sheet| End-of-Life Care for People Who Have Cancer|
|https://www.cancer.gov/about-cancer/advanced-cancer/planning/end-of-life-pdq|Planning the Transition to End-of-Life Care in Advanced Cancer|

```
```gherkin
Scenario Outline: The user views a definition with a drug summary link resource
  Given the user is viewing the definition with the pretty url "hpv"
  Then there is a heading on the page with "More Information"
  And there is a link to "<link>" with the text "<text>"      

Examples:
|link|text|
|https://www.cancer.gov/about-cancer/causes-prevention/risk/infectious-agents/hpv-and-cancer|HPV and Cancer|
|https://www.cancer.gov/about-cancer/causes-prevention/risk/infectious-agents/hpv-vaccine-fact-sheet|Human Papillomavirus (HPV) Vaccines|
|https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-bivalent-vaccine|Recombinant Human Papillomavirus (HPV) Bivalent Vaccine|
|https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-quadrivalent-vaccine|Recombinant Human Papillomavirus (HPV) Quadrivalent Vaccine|

```
```gherkin
Scenario: The user views a definition with an external link resource
  Given the user is viewing the definition with the pretty url "lung-cancer"
  Then there is a heading on the page with "More Information"
      And there is a link to "https://www.cancer.gov/types/lung" with the text "Lung Cancer"
```
```gherkin
Scenario: The user views a definition with no related resources
  Given the user is viewing the definition with the pretty url "stage-ii-cutaneous-t-cell-lymphoma"
  Then there is no text on the page with More Information (More Information does not appear as a label)
```
```gherkin
Scenario: The user views a definition with media and with no related resources
  Given the user is viewing the definition with the pretty url "philadelphia chromosome"
  Then there is no text on the page with More Information (More Information does not appear as a label)
  Then media appears
```

```gherkin
Scenario: The user views a spanish definition with glossary resources
  Given the user is viewing the definition with the pretty url "tejido-graso-de-la-mama"
  Then there is a heading on the page with "Más información"
     And there is a link to a definition with the pretty url "densidad-de-la-mama" and the text "densidad de la mama" following the text "Definición de:"
```

### Resources:
* Glossary API Object Model: https://github.com/NCIOCPL/glossary-api/wiki/Glossary
* Legacy Web Pages: 
   * [terminal-cancer](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/terminal-cancer)
   * [fatty-breast-tissue](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/fatty-breast-tissue)
   * [hpv](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/hpv)
   * [lung-cancer](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/lung-cancer)
   * [stage-ii-cutaneous-t-cell-lymphoma](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/stage-ii-cutaneous-t-cell-lymphoma)
   * [tejido-graso-de-la-mama](https://www.cancer.gov/espanol/publicaciones/diccionario/def/tejido-graso-de-la-mama)

### Notes
* There are 4 types of Related Resources, which have two different structures (this is all in the API, FYI)
   * LinkResource - these items have a URL for an anchor's href and a string to use for the anchors text.
   * GlossaryResource - these are references to other terms *within* the same dictionary. They have a TermID, PrettyUrlName, Audience and Term Name. The app should be able to use the ID/PrettyUrlName to generate the href, and the Term Name can be text. 

---

### Prerequisites
- [x] Basic Term Page (#15)

### Tasks
- [x] E2E tests

### Technical Notes
- More notes, or technical nuances/direction

**Comment by kate-mashkina** [comment]
@bryanpizzillo  Scenario with 'termal-cancer' pretty url has two links with corresponding texts - the step does not reflect that. I will go ahead and format it to check both links and both texts

**Comment by bryanpizzillo** [comment]
Cool. I was not caring about testing all the links, I was interested in the TYPE of the links. However it does not hurt
