### ISSUE TITLE
Spike Story: App Modules Need To be Translatable

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#4]
### Notes

* This is a spike story to ensure that the app module framework we created can be translated into Spanish successfully, and then a Spanish App Module can be created and appears on Cancer.gov correctly.  @bryanpizzillo for more details please!
---
## Results
* App modules are translatable today. The dictionaries are already translated.
* The config, app module, and even the template fields are translatable
* App module routing works with multiple urls
* The language toggle does not work correctly even before doing any fancy route handling.
   * Additionally, it does not support any fancy route handling either.   Spike #44 has been created to further investigate.

**Comment by bkline** [comment]
> user saves content And user is able to see the translated content on the front-end

Not sure how this would actually work, in a world where dictionary content is updated asynchronously from PDQ on a nightly schedule.

**Comment by VictoriaSunNIH** [comment]
Closing - we have results and opened other spikes as noted.
