### ISSUE TITLE
Spike: Determine approach for testing analytics

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#44]
## In order to test analytics, our cucumber scripts need to validate that the correct Adobe analytics are being captured.

> **TIMEBOX** 2 day

### Expected Deliverables:
- [x] Prototype code for handling the spies
- [x] Documentation on how to 

### Additional Notes:
* Questions - I cannot find a way to capture emitted events with Cypress (e.g. events=event1, event47=16)

### Results of Spike
https://github.com/NCIOCPL/glossary-app/wiki/Google-Analytics-Testing

**Comment by kate-mashkina** [comment]
@bryanpizzillo can you take a look at Result of Spike (Wiki Page link) to determine if this will be enough for our e2e purpose?

**Comment by amydugan** [comment]
Results of Spike here: https://github.com/NCIOCPL/glossary-app/wiki/Google-Analytics-Testing
