### ISSUE TITLE
Spike: Index.html application variables

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#75]
## In order to change the dictionary and/or language options for the react app, the developer needs to see if webpack can handle index.html files. 
> **TIMEBOX** 1 story point

***NOTE: a spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by arcepaul** [comment]
So setting up different entry points (ex. espanol.html) is possible via setting up separate instances of HTML webpack plugin like so: 
```module.exports = {
  entry: {
    'main': '...src/index',
    'spanish': '...src/index'
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: false,
      chunks: ['main'],
      filename: '/build/index.html'
    }),
    new HtmlWebpackPlugin({
      inject: false,
      chunks: ['spanish'],
      filename: '/build/espanol.html'
    })
  ]
};```

 Adding a script block at the top of the index files, (e.g window.REACT_APP_DEV_VARIANT) and pulling them in like we do on src/index.js:110 for non-prod builds

**Comment by VictoriaSunNIH** [comment]
Results as listed above. Closing as completed.
